### ISSUE TITLE
Very trivial issue - argparse.version

### ISSUE THREAD

**Issue by stone1343** [mpeterv/argparse#21]
Hi, I love that you've added argparse.version in v0.6.0, just a very trivial comment, I think the "Lua way" to do this is argparse._VERSION.

Feel free to reject this defect if I'm off-base.

Thanks

Jeff

**Comment by daurnimator** [comment]
`_VERSION` is sort of a weird one: it was the traditional name for the field; yet Lua has always reserved names starting with underscore. With the Lua 5.3 release, this was formalised better in [the lua manual](https://www.lua.org/manual/5.3/manual.html#3.1):
> As a convention, programs should avoid creating names that start with an underscore followed by one or more uppercase letters (such as `_VERSION`). 

I would say that is definitive enough to reject this proposal. (Could you please close this issue?)

**Comment by stone1343** [comment]
Thanks for feedback, closing as requested
