### ISSUE TITLE
How to stop handling options after an argument?

### ISSUE THREAD

**Issue by edubart** [mpeterv/argparse#23]
I am unable to stop handling option parsing after some argument. This is useful for creating scripts that need to pass arguments when invoking shell commands. For example this sample code does not work as intended:

```lua
local argparser = require'argparse'()
argparser:flag('-s --something', "Something flag")
argparser:argument("input", "Input"):action(function()
  argparser:handle_options(false)
end)
argparser:argument("args"):args("*"):action('concat')
local options = argparser:parse()
print(table.concat(options.args, ' '))
```

When running with `lua test.lua -s file a1 a2 -c`:
```
Usage: playground/playground.lua [-s] [-h] <input> [<args>] ...

Error: unknown option '-c'
Did you mean one of these: '-h' '-s'?
```

What I would expect is when input is consumed the `argparser:handle_options(false)` would cancel argparser to handle options and the above example would outputs `a1 a2 -c`.

**Comment by daurnimator** [comment]
@edubart did you get a solution for this?

**Comment by p-ouellette** [comment]
It's not possible to disable option handling after parsing has started.
You could use `lua test.lua -s file -- a1 a2 -c` instead.

**Comment by edubart** [comment]
@daurnimator I made a "hack" by injecting `--` into the args just after parsing the first input argument. Not a pretty solution, but worked for me, the code can be seen here:

https://github.com/edubart/euluna-lang/blob/master/euluna/configer.lua#L38
