### ISSUE TITLE
choices property is not recognized

### ISSUE THREAD

**Issue by Sledmine** [mpeterv/argparse#24]
Reading "the docs" of the argparse it says there is a property on every argument called choices, where you can set wich values are accepted for that argument, but that property doesn't exist

**Comment by Sledmine** [comment]
My bad, I saw that the documentation covered on the docs is for the luarocks version, getting that version now!

**Comment by sundayz** [comment]
The luarocks package doesn't seem to have the choices() function either, and both the github code and luarocks code are version 0.6.0

**Comment by p-ouellette** [comment]
Version 0.7.0 is at https://luarocks.org/modules/argparse/argparse
