### ISSUE TITLE
Argument choices?

### ISSUE THREAD

**Issue by VADemon** [mpeterv/argparse#25]
I was going by the [documentation](https://argparse.readthedocs.io/en/stable/arguments.html#setting-argument-choices) and wanted to restrict a certain argument to only a few choices as described.

However it appears that there's no "choices" whatsoever in `argparse.lua`? CTRL+F for `choices` `choice` - 0 matches.

This leaves me no choice but to forget about this feature.

```lua
argparse = require("lib.argparse")

local parser = argparse("name", "descr", "footer")
parser:argument("-s --site")
	:choices{"auto","two","three"}
	:description("Type of link")
```

`L4: attempt to call a nil value (method 'choices')`

What happened there with the doc/lib?

**Comment by p-ouellette** [comment]
argparse is now maintained by luarocks: https://github.com/luarocks/argparse

**Comment by VADemon** [comment]
Thanks, since I can't change the title, I think it would be nice if you created an issue to notify people :)
