### ISSUE TITLE
Allow changing help option argument

### ISSUE THREAD

**Issue by michaelmior** [mpeterv/argparse#4]
In some cases, I may want to use `-h` to refer to something else. It would be nice if `argparse` would at least detect this and disable the short form of the `--help` option. Alternatively, perhaps it could be possible to specify a different option to be used for the help message.

**Comment by mpeterv** [comment]
Like this? http://argparse.readthedocs.org/en/0.5.0/misc.html#overwriting-default-help-option

**Comment by michaelmior** [comment]
Whoops. Sorry about that. I obviously should have RTFM. Thanks!

**Comment by mpeterv** [comment]
No problem! =D
