### ISSUE TITLE
Tutorial for v0.3.1 is disappeared

### ISSUE THREAD

**Issue by mondwan** [mpeterv/argparse#5]
```
$> luarocks list
argparse
   0.3.1-1 (installed) - /usr/local/lib/luarocks/rocks
```

[Old link][1] is dead.
[1]: http://mpeterv.github.io/argparse/

However, [official website][2] from readthedocs does not has a page for `v0.3.1`.

[2]: http://argparse.readthedocs.org/en/0.5.0/

**Comment by mpeterv** [comment]
I'll restore the old page and add a notice. I don't think it's possible to add docs to readthedocs.org for existing tags. You can use `luarocks doc argparse` to view the docs for your version though, assuming your LuaRocks is not too old.

**Comment by mpeterv** [comment]
Old page restored.
